name: Fiyat Bot Çalıştır

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Gerekli Paketleri Kur
      run: |
        pip install selenium pandas python-telegram-bot

    - name: Chrome ve Doğru ChromeDriver Kurulumu
      run: |
        sudo apt update
        sudo apt install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+' | head -1)
        CHROMEDRIVER_VERSION=$(curl -s "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION}")
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Fiyat Botunu Çalıştır
      run: |
        python fiyat_bot.py
